

services:
  db:
    image: postgres:15-alpine
    container_name: cfa_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cfa-network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: cfa_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - cfa-network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: cfa_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - cfa-network
    depends_on:
      - backend

  db-admin:
    image: adminer
    container_name: cfa_db_admin
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cfa-network

networks:
  cfa-network:
    driver: bridge

volumes:
  postgres_data:
